public: false
category: "reference and outreach"
tags:
  - "policy"
title: "Employee Handbook"
description: "Rockefeller Archive Center Employee Handbook"
pages:
  - ["General Information", "index"]
  - ["Employment Policies", "policies"]
  - ["Employment Practices", "practices"]
  - ["Compensation", "compensation"]
  - ["Employee Benefits and Time Off", "benefits-time-off"]
  - ["Staff Development and Training", "staff-development-training"]
  - ["Office Policy and Procedures", "office-policies-procedures"]
  - ["Information Technology", "information-technology"]
