public:
type: "docs"
category: "reference and outreach"
tags:

title: "Employee Handbook"
description: "Rockefeller Archive Center Employee Handbook"
pages:
  - ["Employee Handbook", "index"]
  - ["Policies", "policies"]
  - ["Practices", "practices"]
  - ["Compensation", "compensation"]
  - ["Employee Benefits and Time Off" 
- ["Planning", "planning"]
  - ["Processing", "processing"]
